# Generated by Django 4.2.13 on 2024-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='address',
            field=models.CharField(default='dnm', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='phone_number',
            field=models.CharField(default='555 555 5555', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='tax_number',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
